pipeline {
    agent any
    parameters {
        string(name: "PERSON", defaultValue: "Mr Jenkins", description: "Who should I say hello to?")
    }
    stages {
        stage("scm"){
            steps{
                echo "Hello ${params.PERSON}"
            }
        }
    }
    post {
        success {
            echo "It's all set."
        }
    }
}
