pipeline {
    agent any
    parameters {
        string(name: "StorageCredentialId", defaultValue: "jwstlocala", description: "Azure storage account credential Id")
    }
    stages {
        stage("scm"){
            steps{
                git([url: 'https://github.com/jenkinsci/azure-credentials-plugin.git', branch: 'master'])
            }
        }
        stage("build"){
            steps{
                sh "mvn clean package -Dmaven.test.skip=true"
            }
            post{
                azureUpload storageCredentialId: '${params.StorageCredentialId}', storageType: 'blobstorage', 
                    containerName: 'jenkinstestcontainer', filesPath: '*.hpi'
            }
        }
    }
    post {
        success {
            echo "Build succeeds. It's all set."
        }
    }
}
