pipeline {
    agent any
    parameters {
        string(name: "PERSON", defaultValue: "Mr Jenkins", description: "Who should I say hello to?")
    }
    stages {
        stage("scm"){
            steps{
                git([url: 'https://github.com/juniwang/JavaHelloWorld.git', branch: 'master'])
            }
        }
        stage("build"){
            steps{
                sh "mvn clean package"
            }
        }
    }
    post {
        success {
            echo "Build succeeds. It's all set."
        }
    }
}
